server:
  port: 8085
spring:
  application:
    name: user-service
  profiles:
    active: local

harbor:
  swagger:
    title: 用户相关接口
    desc: "用户相关接口"
    package:
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123

