server:
  port: 8083
spring:
  application:
    name: pay-service
  profiles:
    active: local
  rabbitmq:
    host: 115.190.252.109 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
harbor:
  swagger:
    title: 支付接口测试
    desc: "支付接口测试"
    package: com.harbor.controller
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123